services:
  # Backend Service (Go + Gin)
  - type: web
    name: pizza-billing-backend
    env: go
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: go mod download && go build -o main cmd/server/main.go
    startCommand: ./main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: GIN_MODE
        value: release
      - key: DATABASE_URL
        fromDatabase:
          name: pizza-billing-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://pizza-billing-frontend.onrender.com

  # Frontend Service (React)
  - type: web
    name: pizza-billing-frontend
    env: static
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://pizza-billing-backend.onrender.com/api

databases:
  - name: pizza-billing-db
    databaseName: pizza_billing
    user: pizza_user
    plan: free